export const LANG_KEYS = {
  ASSEMBLY: 45,
  BASH: 46,
  BASIC: 47,
  C_CLANG_18: 104,
  C_CLANG_19: 110,
  C_CLANG_7: 75,
  CPP_CLANG_7: 76,
  C_GCC_14: 103,
  CPP_GCC_14: 105,
  C_GCC_7: 48,
  CPP_GCC_7: 52,
  C_GCC_8: 49,
  CPP_GCC_8: 53,
  C_GCC_9: 50,
  CPP_GCC_9: 54,
  CLOJURE: 86,
  CSHARP_MONO: 51,
  COBOL: 77,
  COMMON_LISP: 55,
  DART: 90,
  D_DMD: 56,
  ELIXIR: 57,
  ERLANG: 58,
  EXECUTABLE: 44,
  FSHARP: 87,
  FORTRAN: 59,
  GO_1_13: 60,
  GO_1_18: 95,
  GO_1_22: 106,
  GO_1_23: 107,
  GROOVY: 88,
  HASKELL: 61,
  JAVAFX: 96,
  JAVA_JDK_17: 91,
  JAVA_OPENJDK_13: 92,
  JAVASCRIPT_NODE_12: 93,
  JAVASCRIPT_NODE_18: 94,
  JAVASCRIPT_NODE_20: 95,
  JAVASCRIPT_NODE_22: 96,
  KOTLIN_1_3: 97,
  KOTLIN_2_1: 98,
  LUA: 99,
  MULTI_FILE_PROGRAM: 100,
  OBJECTIVE_C: 101,
  OCAML: 102,
  OCTAVE: 103,
  PASCAL: 104,
  PERL: 105,
  PHP_7: 106,
  PHP_8: 107,
  PLAIN_TEXT: 108,
  PROLOG: 109,
  PYTHON_2: 110,
  PYTHON_3_11: 111,
  PYTHON_3_12: 112,
  PYTHON_3_13: 113,
  PYTHON_3_8: 114,
  R_4: 115,
  R_4_4: 116,
  RUBY: 117,
  RUST_1_40: 118,
  RUST_1_85: 119,
  SCALA: 120,
  SQL: 121,
  SWIFT: 122,
  TYPESCRIPT_3: 123,
  TYPESCRIPT_5: 124,
  TYPESCRIPT_5_6: 125,
  VISUAL_BASIC_NET: 126,
};

export const LANGUAGES_MAP: Map<number, { label: string; value: number }> =
  new Map([
    [
      LANG_KEYS.ASSEMBLY,
      { label: "Assembly (NASM 2.14.02)", value: LANG_KEYS.ASSEMBLY },
    ],
    [LANG_KEYS.BASH, { label: "Bash (5.0.0)", value: LANG_KEYS.BASH }],
    [LANG_KEYS.BASIC, { label: "Basic (FBC 1.07.1)", value: LANG_KEYS.BASIC }],
    [
      LANG_KEYS.C_CLANG_18,
      { label: "C (Clang 18.1.8)", value: LANG_KEYS.C_CLANG_18 },
    ],
    [
      LANG_KEYS.C_CLANG_19,
      { label: "C (Clang 19.1.7)", value: LANG_KEYS.C_CLANG_19 },
    ],
    [
      LANG_KEYS.C_CLANG_7,
      { label: "C (Clang 7.0.1)", value: LANG_KEYS.C_CLANG_7 },
    ],
    [
      LANG_KEYS.CPP_CLANG_7,
      { label: "C++ (Clang 7.0.1)", value: LANG_KEYS.CPP_CLANG_7 },
    ],
    [
      LANG_KEYS.C_GCC_14,
      { label: "C (GCC 14.1.0)", value: LANG_KEYS.C_GCC_14 },
    ],
    [
      LANG_KEYS.CPP_GCC_14,
      { label: "C++ (GCC 14.1.0)", value: LANG_KEYS.CPP_GCC_14 },
    ],
    [LANG_KEYS.C_GCC_7, { label: "C (GCC 7.4.0)", value: LANG_KEYS.C_GCC_7 }],
    [
      LANG_KEYS.CPP_GCC_7,
      { label: "C++ (GCC 7.4.0)", value: LANG_KEYS.CPP_GCC_7 },
    ],
    [LANG_KEYS.C_GCC_8, { label: "C (GCC 8.3.0)", value: LANG_KEYS.C_GCC_8 }],
    [
      LANG_KEYS.CPP_GCC_8,
      { label: "C++ (GCC 8.3.0)", value: LANG_KEYS.CPP_GCC_8 },
    ],
    [LANG_KEYS.C_GCC_9, { label: "C (GCC 9.2.0)", value: LANG_KEYS.C_GCC_9 }],
    [
      LANG_KEYS.CPP_GCC_9,
      { label: "C++ (GCC 9.2.0)", value: LANG_KEYS.CPP_GCC_9 },
    ],
    [
      LANG_KEYS.CLOJURE,
      { label: "Clojure (1.10.1)", value: LANG_KEYS.CLOJURE },
    ],
    [
      LANG_KEYS.CSHARP_MONO,
      { label: "C# (Mono 6.6.0.161)", value: LANG_KEYS.CSHARP_MONO },
    ],
    [
      LANG_KEYS.COBOL,
      { label: "COBOL (GnuCOBOL 2.2)", value: LANG_KEYS.COBOL },
    ],
    [
      LANG_KEYS.COMMON_LISP,
      { label: "Common Lisp (SBCL 2.0.0)", value: LANG_KEYS.COMMON_LISP },
    ],
    [LANG_KEYS.DART, { label: "Dart (2.19.2)", value: LANG_KEYS.DART }],
    [LANG_KEYS.D_DMD, { label: "D (DMD 2.089.1)", value: LANG_KEYS.D_DMD }],
    [LANG_KEYS.ELIXIR, { label: "Elixir (1.9.4)", value: LANG_KEYS.ELIXIR }],
    [LANG_KEYS.ERLANG, { label: "Erlang (OTP 22.2)", value: LANG_KEYS.ERLANG }],
    [
      LANG_KEYS.EXECUTABLE,
      { label: "Executable", value: LANG_KEYS.EXECUTABLE },
    ],
    [
      LANG_KEYS.FSHARP,
      { label: "F# (.NET Core SDK 3.1.202)", value: LANG_KEYS.FSHARP },
    ],
    [
      LANG_KEYS.FORTRAN,
      { label: "Fortran (GFortran 9.2.0)", value: LANG_KEYS.FORTRAN },
    ],
    [LANG_KEYS.GO_1_13, { label: "Go (1.13.5)", value: LANG_KEYS.GO_1_13 }],
    [LANG_KEYS.GO_1_18, { label: "Go (1.18.5)", value: LANG_KEYS.GO_1_18 }],
    [LANG_KEYS.GO_1_22, { label: "Go (1.22.0)", value: LANG_KEYS.GO_1_22 }],
    [LANG_KEYS.GO_1_23, { label: "Go (1.23.5)", value: LANG_KEYS.GO_1_23 }],
    [LANG_KEYS.GROOVY, { label: "Groovy (3.0.3)", value: LANG_KEYS.GROOVY }],
    [
      LANG_KEYS.HASKELL,
      { label: "Haskell (GHC 8.8.1)", value: LANG_KEYS.HASKELL },
    ],
    [
      LANG_KEYS.JAVAFX,
      { label: "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)", value: LANG_KEYS.JAVAFX },
    ],
    [
      LANG_KEYS.JAVA_JDK_17,
      { label: "Java (JDK 17.0.6)", value: LANG_KEYS.JAVA_JDK_17 },
    ],
    [
      LANG_KEYS.JAVA_OPENJDK_13,
      { label: "Java (OpenJDK 13.0.1)", value: LANG_KEYS.JAVA_OPENJDK_13 },
    ],
    [
      LANG_KEYS.JAVASCRIPT_NODE_12,
      {
        label: "JavaScript (Node.js 12.14.0)",
        value: LANG_KEYS.JAVASCRIPT_NODE_12,
      },
    ],
    [
      LANG_KEYS.JAVASCRIPT_NODE_18,
      {
        label: "JavaScript (Node.js 18.15.0)",
        value: LANG_KEYS.JAVASCRIPT_NODE_18,
      },
    ],
    [
      LANG_KEYS.JAVASCRIPT_NODE_20,
      {
        label: "JavaScript (Node.js 20.17.0)",
        value: LANG_KEYS.JAVASCRIPT_NODE_20,
      },
    ],
    [
      LANG_KEYS.JAVASCRIPT_NODE_22,
      {
        label: "JavaScript (Node.js 22.08.0)",
        value: LANG_KEYS.JAVASCRIPT_NODE_22,
      },
    ],
    [
      LANG_KEYS.KOTLIN_1_3,
      { label: "Kotlin (1.3.70)", value: LANG_KEYS.KOTLIN_1_3 },
    ],
    [
      LANG_KEYS.KOTLIN_2_1,
      { label: "Kotlin (2.1.10)", value: LANG_KEYS.KOTLIN_2_1 },
    ],
    [LANG_KEYS.LUA, { label: "Lua (5.3.5)", value: LANG_KEYS.LUA }],
    [
      LANG_KEYS.MULTI_FILE_PROGRAM,
      { label: "Multi-file program", value: LANG_KEYS.MULTI_FILE_PROGRAM },
    ],
    [
      LANG_KEYS.OBJECTIVE_C,
      { label: "Objective-C (Clang 7.0.1)", value: LANG_KEYS.OBJECTIVE_C },
    ],
    [LANG_KEYS.OCAML, { label: "OCaml (4.09.0)", value: LANG_KEYS.OCAML }],
    [LANG_KEYS.OCTAVE, { label: "Octave (5.1.0)", value: LANG_KEYS.OCTAVE }],
    [
      LANG_KEYS.PASCAL,
      { label: "Pascal (FPC 3.0.4)", value: LANG_KEYS.PASCAL },
    ],
    [LANG_KEYS.PERL, { label: "Perl (5.28.1)", value: LANG_KEYS.PERL }],
    [LANG_KEYS.PHP_7, { label: "PHP (7.4.1)", value: LANG_KEYS.PHP_7 }],
    [LANG_KEYS.PHP_8, { label: "PHP (8.3.11)", value: LANG_KEYS.PHP_8 }],
    [
      LANG_KEYS.PLAIN_TEXT,
      { label: "Plain Text", value: LANG_KEYS.PLAIN_TEXT },
    ],
    [
      LANG_KEYS.PROLOG,
      { label: "Prolog (GNU Prolog 1.4.5)", value: LANG_KEYS.PROLOG },
    ],
    [
      LANG_KEYS.PYTHON_2,
      { label: "Python (2.7.17)", value: LANG_KEYS.PYTHON_2 },
    ],
    [
      LANG_KEYS.PYTHON_3_11,
      { label: "Python (3.11.2)", value: LANG_KEYS.PYTHON_3_11 },
    ],
    [
      LANG_KEYS.PYTHON_3_12,
      { label: "Python (3.12.5)", value: LANG_KEYS.PYTHON_3_12 },
    ],
    [
      LANG_KEYS.PYTHON_3_13,
      { label: "Python (3.13.2)", value: LANG_KEYS.PYTHON_3_13 },
    ],
    [
      LANG_KEYS.PYTHON_3_8,
      { label: "Python (3.8.1)", value: LANG_KEYS.PYTHON_3_8 },
    ],
    [LANG_KEYS.R_4, { label: "R (4.0.0)", value: LANG_KEYS.R_4 }],
    [LANG_KEYS.R_4_4, { label: "R (4.4.1)", value: LANG_KEYS.R_4_4 }],
    [LANG_KEYS.RUBY, { label: "Ruby (2.7.0)", value: LANG_KEYS.RUBY }],
    [
      LANG_KEYS.RUST_1_40,
      { label: "Rust (1.40.0)", value: LANG_KEYS.RUST_1_40 },
    ],
    [
      LANG_KEYS.RUST_1_85,
      { label: "Rust (1.85.0)", value: LANG_KEYS.RUST_1_85 },
    ],
    [LANG_KEYS.SCALA, { label: "Scala (2.13.2)", value: LANG_KEYS.SCALA }],
    [LANG_KEYS.SQL, { label: "SQL (SQLite 3.27.2)", value: LANG_KEYS.SQL }],
    [LANG_KEYS.SWIFT, { label: "Swift (5.2.3)", value: LANG_KEYS.SWIFT }],
    [
      LANG_KEYS.TYPESCRIPT_3,
      { label: "TypeScript (3.7.4)", value: LANG_KEYS.TYPESCRIPT_3 },
    ],
    [
      LANG_KEYS.TYPESCRIPT_5,
      { label: "TypeScript (5.0.3)", value: LANG_KEYS.TYPESCRIPT_5 },
    ],
    [
      LANG_KEYS.TYPESCRIPT_5_6,
      { label: "TypeScript (5.6.2)", value: LANG_KEYS.TYPESCRIPT_5_6 },
    ],
    [
      LANG_KEYS.VISUAL_BASIC_NET,
      {
        label: "Visual Basic.Net (vbnc 0.0.0.5943)",
        value: LANG_KEYS.VISUAL_BASIC_NET,
      },
    ],
  ]);
