export type Language = {
  label: string;
  value: number;
};

export const LANG_KEYS = {
  ASSEMBLY: 45,
  BASH: 46,
  BASIC: 47,
  C_CLANG_7: 75,
  CPP_CLANG_7: 76,
  C_GCC_7: 48,
  CPP_GCC_7: 52,
  C_GCC_8: 49,
  CPP_GCC_8: 53,
  C_GCC_9: 50,
  CPP_GCC_9: 54,
  CLOJURE: 86,
  CSHARP_MONO: 51,
  COBOL: 77,
  COMMON_LISP: 55,
  D_DMD: 56,
  ELIXIR: 57,
  ERLANG: 58,
  EXECUTABLE: 44,
  FSHARP: 87,
  FORTRAN: 59,
  GO_1_13: 60,
  GROOVY: 88,
  HASKELL: 61,
  JAVA_OPENJDK_13: 62,
  JAVASCRIPT_NODE_12: 63,
  KOTLIN_1_3: 78,
  LUA: 64,
  OBJECTIVE_C: 79,
  OCAML: 65,
  OCTAVE: 66,
  PASCAL: 67,
  PERL: 85,
  PHP_7: 68,
  PLAIN_TEXT: 43,
  PROLOG: 69,
  PYTHON_2: 70,
  PYTHON_3_8: 71,
  R_4: 80,
  RUBY: 72,
  RUST_1_40: 73,
  SCALA: 81,
  SQL: 82,
  SWIFT: 83,
  TYPESCRIPT_3: 74,
  VISUAL_BASIC_NET: 84,
};

export const LANGUAGES_MAP: Map<number, Language> = new Map([
  [
    LANG_KEYS.ASSEMBLY,
    { label: "Assembly (NASM 2.14.02)", value: LANG_KEYS.ASSEMBLY },
  ],
  [LANG_KEYS.BASH, { label: "Bash (5.0.0)", value: LANG_KEYS.BASH }],
  [LANG_KEYS.BASIC, { label: "Basic (FBC 1.07.1)", value: LANG_KEYS.BASIC }],
  [
    LANG_KEYS.C_CLANG_7,
    { label: "C (Clang 7.0.1)", value: LANG_KEYS.C_CLANG_7 },
  ],
  [
    LANG_KEYS.CPP_CLANG_7,
    { label: "C++ (Clang 7.0.1)", value: LANG_KEYS.CPP_CLANG_7 },
  ],
  [LANG_KEYS.C_GCC_7, { label: "C (GCC 7.4.0)", value: LANG_KEYS.C_GCC_7 }],
  [
    LANG_KEYS.CPP_GCC_7,
    { label: "C++ (GCC 7.4.0)", value: LANG_KEYS.CPP_GCC_7 },
  ],
  [LANG_KEYS.C_GCC_8, { label: "C (GCC 8.3.0)", value: LANG_KEYS.C_GCC_8 }],
  [
    LANG_KEYS.CPP_GCC_8,
    { label: "C++ (GCC 8.3.0)", value: LANG_KEYS.CPP_GCC_8 },
  ],
  [LANG_KEYS.C_GCC_9, { label: "C (GCC 9.2.0)", value: LANG_KEYS.C_GCC_9 }],
  [
    LANG_KEYS.CPP_GCC_9,
    { label: "C++ (GCC 9.2.0)", value: LANG_KEYS.CPP_GCC_9 },
  ],
  [LANG_KEYS.CLOJURE, { label: "Clojure (1.10.1)", value: LANG_KEYS.CLOJURE }],
  [
    LANG_KEYS.CSHARP_MONO,
    { label: "C# (Mono 6.6.0.161)", value: LANG_KEYS.CSHARP_MONO },
  ],
  [LANG_KEYS.COBOL, { label: "COBOL (GnuCOBOL 2.2)", value: LANG_KEYS.COBOL }],
  [
    LANG_KEYS.COMMON_LISP,
    { label: "Common Lisp (SBCL 2.0.0)", value: LANG_KEYS.COMMON_LISP },
  ],
  [LANG_KEYS.D_DMD, { label: "D (DMD 2.089.1)", value: LANG_KEYS.D_DMD }],
  [LANG_KEYS.ELIXIR, { label: "Elixir (1.9.4)", value: LANG_KEYS.ELIXIR }],
  [LANG_KEYS.ERLANG, { label: "Erlang (OTP 22.2)", value: LANG_KEYS.ERLANG }],
  [LANG_KEYS.EXECUTABLE, { label: "Executable", value: LANG_KEYS.EXECUTABLE }],
  [
    LANG_KEYS.FSHARP,
    { label: "F# (.NET Core SDK 3.1.202)", value: LANG_KEYS.FSHARP },
  ],
  [
    LANG_KEYS.FORTRAN,
    { label: "Fortran (GFortran 9.2.0)", value: LANG_KEYS.FORTRAN },
  ],
  [LANG_KEYS.GO_1_13, { label: "Go (1.13.5)", value: LANG_KEYS.GO_1_13 }],
  [LANG_KEYS.GROOVY, { label: "Groovy (3.0.3)", value: LANG_KEYS.GROOVY }],
  [
    LANG_KEYS.HASKELL,
    { label: "Haskell (GHC 8.8.1)", value: LANG_KEYS.HASKELL },
  ],
  [
    LANG_KEYS.JAVA_OPENJDK_13,
    { label: "Java (OpenJDK 13.0.1)", value: LANG_KEYS.JAVA_OPENJDK_13 },
  ],
  [
    LANG_KEYS.JAVASCRIPT_NODE_12,
    {
      label: "JavaScript (Node.js 12.14.0)",
      value: LANG_KEYS.JAVASCRIPT_NODE_12,
    },
  ],
  [
    LANG_KEYS.KOTLIN_1_3,
    { label: "Kotlin (1.3.70)", value: LANG_KEYS.KOTLIN_1_3 },
  ],
  [LANG_KEYS.LUA, { label: "Lua (5.3.5)", value: LANG_KEYS.LUA }],
  [
    LANG_KEYS.OBJECTIVE_C,
    { label: "Objective-C (Clang 7.0.1)", value: LANG_KEYS.OBJECTIVE_C },
  ],
  [LANG_KEYS.OCAML, { label: "OCaml (4.09.0)", value: LANG_KEYS.OCAML }],
  [LANG_KEYS.OCTAVE, { label: "Octave (5.1.0)", value: LANG_KEYS.OCTAVE }],
  [LANG_KEYS.PASCAL, { label: "Pascal (FPC 3.0.4)", value: LANG_KEYS.PASCAL }],
  [LANG_KEYS.PERL, { label: "Perl (5.28.1)", value: LANG_KEYS.PERL }],
  [LANG_KEYS.PHP_7, { label: "PHP (7.4.1)", value: LANG_KEYS.PHP_7 }],
  [LANG_KEYS.PLAIN_TEXT, { label: "Plain Text", value: LANG_KEYS.PLAIN_TEXT }],
  [
    LANG_KEYS.PROLOG,
    { label: "Prolog (GNU Prolog 1.4.5)", value: LANG_KEYS.PROLOG },
  ],
  [LANG_KEYS.PYTHON_2, { label: "Python (2.7.17)", value: LANG_KEYS.PYTHON_2 }],
  [
    LANG_KEYS.PYTHON_3_8,
    { label: "Python (3.8.1)", value: LANG_KEYS.PYTHON_3_8 },
  ],
  [LANG_KEYS.R_4, { label: "R (4.0.0)", value: LANG_KEYS.R_4 }],
  [LANG_KEYS.RUBY, { label: "Ruby (2.7.0)", value: LANG_KEYS.RUBY }],
  [LANG_KEYS.RUST_1_40, { label: "Rust (1.40.0)", value: LANG_KEYS.RUST_1_40 }],
  [LANG_KEYS.SCALA, { label: "Scala (2.13.2)", value: LANG_KEYS.SCALA }],
  [LANG_KEYS.SQL, { label: "SQL (SQLite 3.27.2)", value: LANG_KEYS.SQL }],
  [LANG_KEYS.SWIFT, { label: "Swift (5.2.3)", value: LANG_KEYS.SWIFT }],
  [
    LANG_KEYS.TYPESCRIPT_3,
    { label: "TypeScript (3.7.4)", value: LANG_KEYS.TYPESCRIPT_3 },
  ],
  [
    LANG_KEYS.VISUAL_BASIC_NET,
    {
      label: "Visual Basic.Net (vbnc 0.0.0.5943)",
      value: LANG_KEYS.VISUAL_BASIC_NET,
    },
  ],
]);

export const JUDGE0_TO_MONACO_MAPPING: Map<number, string> = new Map([
  [LANG_KEYS.PLAIN_TEXT, "plaintext"],
  [LANG_KEYS.EXECUTABLE, "plaintext"],
  [LANG_KEYS.ASSEMBLY, "asm"],
  [LANG_KEYS.BASH, "shell"],
  [LANG_KEYS.BASIC, "vb"],
  [LANG_KEYS.C_GCC_7, "c"],
  [LANG_KEYS.C_GCC_8, "c"],
  [LANG_KEYS.C_GCC_9, "c"],
  [LANG_KEYS.CSHARP_MONO, "csharp"],
  [LANG_KEYS.CPP_GCC_7, "cpp"],
  [LANG_KEYS.CPP_GCC_8, "cpp"],
  [LANG_KEYS.CPP_GCC_9, "cpp"],
  [LANG_KEYS.COMMON_LISP, "scheme"],
  [LANG_KEYS.D_DMD, "d"],
  [LANG_KEYS.ELIXIR, "elixir"],
  [LANG_KEYS.ERLANG, "erlang"],
  [LANG_KEYS.FORTRAN, "fortran"],
  [LANG_KEYS.GO_1_13, "go"],
  [LANG_KEYS.HASKELL, "haskell"],
  [LANG_KEYS.JAVA_OPENJDK_13, "java"],
  [LANG_KEYS.JAVASCRIPT_NODE_12, "javascript"],
  [LANG_KEYS.LUA, "lua"],
  [LANG_KEYS.OCAML, "ocaml"],
  [LANG_KEYS.OCTAVE, "matlab"],
  [LANG_KEYS.PASCAL, "pascal"],
  [LANG_KEYS.PHP_7, "php"],
  [LANG_KEYS.PROLOG, "prolog"],
  [LANG_KEYS.PYTHON_2, "python"],
  [LANG_KEYS.PYTHON_3_8, "python"],
  [LANG_KEYS.RUBY, "ruby"],
  [LANG_KEYS.RUST_1_40, "rust"],
  [LANG_KEYS.TYPESCRIPT_3, "typescript"],
  [LANG_KEYS.C_CLANG_7, "c"],
  [LANG_KEYS.CPP_CLANG_7, "cpp"],
  [LANG_KEYS.COBOL, "cobol"],
  [LANG_KEYS.KOTLIN_1_3, "kotlin"],
  [LANG_KEYS.OBJECTIVE_C, "objective-c"],
  [LANG_KEYS.R_4, "r"],
  [LANG_KEYS.SCALA, "scala"],
  [LANG_KEYS.SQL, "sql"],
  [LANG_KEYS.SWIFT, "swift"],
  [LANG_KEYS.VISUAL_BASIC_NET, "vb"],
  [LANG_KEYS.PERL, "perl"],
  [LANG_KEYS.CLOJURE, "clojure"],
  [LANG_KEYS.FSHARP, "fsharp"],
  [LANG_KEYS.GROOVY, "groovy"],
]);
